"""add paper trading tables

Revision ID: b005620d49fe
Revises: 8f8e4d74ffd0
Create Date: 2026-06-12 11:59:27.301235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b005620d49fe'
down_revision = '8f8e4d74ffd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('equity_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('margin_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('pnl_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('close_reason', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_user_id'), ['user_id'], unique=False)

    op.create_table('paper_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('strategy_reason', sa.Text(), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_signals_user_id'), ['user_id'], unique=False)

    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('margin_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('pnl_usdt', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_symbol'))

    op.drop_table('paper_trades')
    with op.batch_alter_table('paper_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_signals_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_signals_symbol'))

    op.drop_table('paper_signals')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_status'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_accounts_user_id'))

    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
